### ISSUE TITLE
Spy bug

### ISSUE THREAD

**Issue by SmigloNPC** [ThePlay3r/Marriage#4] opened 2020-11-12 18:51 UTC
When I have spy activated I don't see message from marriage chat. <br>But on server logs I see that /marry c have been used by players<br>
I have all permission on server and there is no errors on console

**Comment by ThePlay3r** [comment] 2020-11-13 04:47
I'm sorry for the inconvenience.

I found the cause of the issue and will fix it in the upcoming weekend, for now, I would recommend **not using** the spy feature at all.

**Comment by ThePlay3r** [comment] 2020-11-15 00:29
Fixed in the [1.7 version](https://github.com/ThePlay3r/Marriage/releases/tag/1.7).

**Closed as completed by ThePlay3r** 2020-11-15 00:29 UTC
Labels: bug
